language: node_js
node_js:
  - "6.9.1"

install:
  - npm i

before_script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true

  local_dir: dist

  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  
  on:
    branch: master